FROM node:16-alpine3.11 as build
WORKDIR /app
COPY ./frontend/ ./
RUN npm ci --silent
RUN npm run build

FROM nginx:stable-alpine
RUN mkdir -p /vol/static/js
RUN mkdir -p /vol/static/css
RUN mkdir -p /vol/static/media

COPY --from=build /app/build /usr/share/nginx/html

COPY ./proxy/default.conf /etc/nginx/conf.d/default.conf
COPY ./proxy/uwsgi_params /etc/nginx/uwsgi_params