FROM python:3
ENV PYTHONUNBUFFERED=1

COPY ./backend/requirements.txt /requirements.txt
RUN pip install -r requirements.txt

WORKDIR /backend
COPY ./backend /backend/

COPY ./scripts /scripts
RUN chmod +x /scripts/*

RUN mkdir -p /vol/web/media
RUN mkdir -p /vol/web/static

ENV PATH="/scripts:${PATH}"
CMD ["entrypoint.sh"]